@extends('_layouts.default')
@section('content')
<p class="p1" style="font-weight: bold; text-align: center"><span class="s1"><strong>Instructions to Users: Online Flexible Test of Attention Variables (Flexible TOVA)</strong></span></p>
<p class="p2"><span class="s1"><strong>How to buy licenses: </strong></span></p>
<p class="p2"><span class="s1">To get access to the online Flexible TOVA you have to buy our licenses. You should refer to the following website address: www. &hellip;.com. At the home page you should click the Flexible TOVA from the Software Menu, and then select the licenses pricing. You should select and pay for one of the licenses. Your Email address would be used as your username. You will also receive a password on your Email address. You can login to your account using your username and password until your password has been expired. </span></p>
<p class="p2"><span class="s1"><strong>To start with the online Flexible TOVA:</strong></span></p>
<ol class="ol1">
<li class="li2"><span class="s1">First you should create a new group. From the &ldquo;Group&rdquo; menu on the homepage of our website, click the Add button. Type the name of the group you want to create in the given box and hit the Enter or click the add button. You can also click the cancel button, to cancel the &ldquo;add group&rdquo; process. </span></li>
<li class="li2"><span class="s1">You should now, add the name of a participant to one of the previously added groups. From the participants menu on the homepage, click the Add button. Select the name of one of the previously added groups from the drop down menu. Complete the identity information of the participant and then hit the Enter or click the add button. Please note that ID number should not be more or less than 10 characters. </span></li>
<li class="li2"><span class="s1">Deleting a group or a participant: you should be cautious when you choose to delete a group or a participant. Because this will permanently delete all the saved data of a particular group or participant. From the &ldquo;Groups&rdquo; or &ldquo;Participants&rdquo; menu on the homepage, click the &ldquo;List&rdquo; button and then select the name of the group or the participant you want to delete, from the drop down menu. Finally, click the &ldquo;Remove&rdquo; button. </span></li>
</ol>
<p class="p2"><span class="s1"><strong>To start testing:</strong></span></p>
<ol class="ol1">
<li class="li2"><span class="s1">Click &ldquo;Start test&rdquo; from the test menu on the homepage. Insert the following settings on the opened window: </span></li>
</ol>
<p class="p3"><span class="s1"><strong>Selecting the Test Type: </strong>you can select visual or auditory mode of the test.</span></p>
<p class="p3"><span class="s1"><strong>Selecting the Stimulus Type: </strong>if you have chosen the visual mode, you can select one of the following stimulus types from the drop down menu: Alphabet, Numbers, or Shapes. Also, if you have chosen the auditory mode, you can select one of the following stimulus types from the drop down menu: Alphabet, Numbers, or Animal Sounds.</span></p>
<p class="p3"><span class="s1"> <strong>Selecting the Target Stimulus: </strong>target stimulus is a predetermined stimulus to which the participants are supposed to respond, by hitting the &ldquo;Space button&rdquo; on the keypad. On the other hand, when participant are exposed to non-target stimuli, they are supposed not to hit the &ldquo;Space button&rdquo;. Select one of the stimuli from the drop down menu,<em> as a target stimulus</em>. Pay attention, that as you are choosing one the stimuli as your target, that stimulus is presented in visual or auditory mode on the right hand. </span></p>
<p class="p3"><span class="s1"><strong>Selecting the Display Time (DT): </strong>you can choose your preferred DT in Milliseconds (MS) unites. To determine DT, it is enough to type an arbitrary number in the DT box. &ldquo;500&rdquo; has been selected as a default value, which means that the target stimulus, you have just chosen, will be presented for 500 MS (one half of a second) each time during the test administration. <span class="Apple-converted-space">&nbsp; &nbsp;</span></span></p>
<p class="p3"><span class="s1"><strong>Selecting the Inter-Stimulus Interval (ISI): </strong>you can also choose your preferred ISI in MS unites. To determine ISI, it is enough to type an arbitrary number in the ISI box. &ldquo;1000&rdquo; has been selected as a default value, which means that the interval between each two successive stimuli would be 1000 MS (one second) each time during the test administration. <span class="Apple-converted-space">&nbsp; &nbsp;</span></span></p>
<p class="p3"><span class="s1"><strong>Selecting the General Test Variables: </strong></span></p>
<p class="p3"><span class="s1"><strong>Percentage of the Target Stimuli: </strong>you can choose the proportion of the target to non-target stimuli through typing an arbitrary percentage among 10, 20, 30, &hellip;, to 100, in the &ldquo;Target Percentage&rdquo; box. For instance, typing 30 in this box, means that 30 percent of the total stimuli would be target stimuli and the remaining 70 percent would be non-target stimuli. </span></p>
<p class="p3"><span class="s1"><strong>Number of Parts:</strong> each part consists of 150 stimuli. Therefore, if you type, for example, number 1 in the &ldquo;Number of Parts&rdquo; box, it means that 150 stimuli would be presented during the test administration. Of course, you are allowed to insert each preferred correct number (n) in the &ldquo;Number of parts&rdquo; box, which means 150&times;n stimuli would be presented during the test administration.</span></p>
<p class="p3"><span class="s1"><strong>After completing all settings mentioned above, hit the Enter or click the Start button to start the test. </strong><span class="Apple-converted-space">&nbsp; &nbsp;</span></span></p>
@stop
